api_version = "2026-01"
uid = "4682493e-5efb-bbc9-f193-d9a830ea40c8e9f59b9c"

[[extensions]]
type = "ui_extension"
name = "Customer Account — My Returns"
handle = "customer-account-returns"

[extensions.capabilities]
network_access = true
api_access = true

[extensions.settings]
[[extensions.settings.fields]]
key = "app_host"
type = "single_line_text_field"
name = "App host URL"
description = "Production app URL, including https://"

[[extensions.targeting]]
target = "customer-account.order-index.block.render"
module = "./src/Extension.tsx"

[[extensions.targeting]]
target = "customer-account.profile.block.render"
module = "./src/Extension.tsx"
